
eureka:
 instance:
   prefer-ip-address: true
 client:
   fetch-registry : true
   register-with-eureka : true
   service-url:
     defaultZone : http://localhost:8761/eureka/

spring
 datasource:
   url: jdbc:mysql://localhost:3306/auth
   username: root
   password: Pramod@123
 jpa:
   hibernate:
     ddl-auto: update
